/**
 * Builds src/data/samples.ts from real before/after pairs dropped into public/samples/.
 *
 * Naming: <name>-before.(jpg|png|webp) + <name>-after.(jpg|png|webp)
 * Optional captions: public/samples/captions.json  { "<name>": { "title": "...", "style": "Białe tło" } }
 *
 * The landing page shows the "Przed / po" section only when at least one pair exists,
 * so nothing fabricated is ever displayed. Run automatically by `npm run build`.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const samplesDir = resolve(__dirname, '../public/samples')
const outFile = resolve(__dirname, '../src/data/samples.ts')

const IMAGE_RE = /^(.+)-(before|after)\.(jpe?g|png|webp)$/i

let pairs = []
if (existsSync(samplesDir)) {
  const files = readdirSync(samplesDir)
  const byName = new Map()
  for (const file of files) {
    const m = file.match(IMAGE_RE)
    if (!m) continue
    const [, name, kind] = m
    const entry = byName.get(name) ?? {}
    entry[kind.toLowerCase()] = `/samples/${file}`
    byName.set(name, entry)
  }
  let captions = {}
  const captionsFile = resolve(samplesDir, 'captions.json')
  if (existsSync(captionsFile)) {
    try {
      captions = JSON.parse(readFileSync(captionsFile, 'utf-8'))
    } catch (err) {
      console.warn('⚠️  captions.json is not valid JSON – ignoring', err.message)
    }
  }
  pairs = [...byName.entries()]
    .filter(([, e]) => e.before && e.after)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, e]) => ({
      id: name,
      before: e.before,
      after: e.after,
      title: captions[name]?.title ?? name.replace(/[-_]+/g, ' '),
      style: captions[name]?.style ?? null,
    }))
}

const content = `// GENERATED by scripts/generate-samples.js – do not edit by hand.
// Drop <name>-before.jpg / <name>-after.jpg into public/samples/ and rebuild.
export interface SamplePair {
  id: string
  before: string
  after: string
  title: string
  style: string | null
}

export const samplePairs: SamplePair[] = ${JSON.stringify(pairs, null, 2)}
`
writeFileSync(outFile, content, 'utf-8')
console.log(`✅ samples.ts generated (${pairs.length} before/after pairs)`)
