// GENERATED by scripts/generate-samples.js – do not edit by hand.
// Drop <name>-before.jpg / <name>-after.jpg into public/samples/ and rebuild.
export interface SamplePair {
  id: string
  before: string
  after: string
  title: string
  style: string | null
}

export const samplePairs: SamplePair[] = [
  {
    "id": "bluza-biala",
    "before": "/samples/bluza-biala-before.webp",
    "after": "/samples/bluza-biala-after.webp",
    "title": "Bluza z kapturem – Odzież",
    "style": "Białe tło"
  },
  {
    "id": "bluza-w-parku",
    "before": "/samples/bluza-w-parku-before.webp",
    "after": "/samples/bluza-w-parku-after.webp",
    "title": "Bluza z kapturem – Odzież",
    "style": "Produkt w użyciu"
  },
  {
    "id": "projektor",
    "before": "/samples/projektor-before.webp",
    "after": "/samples/projektor-after.webp",
    "title": "Projektor – Elektronika",
    "style": "Białe tło"
  },
  {
    "id": "rolki",
    "before": "/samples/rolki-before.webp",
    "after": "/samples/rolki-after.webp",
    "title": "Rolki – Sport i turystyka",
    "style": "Białe tło"
  }
]
