// GENERATED by scripts/generate-samples.js – do not edit by hand.
// Drop <name>-before.jpg / <name>-after.jpg into public/samples/ and rebuild.
export interface SamplePair {
  id: string
  before: string
  after: string
  title: string
  style: string | null
}

export const samplePairs: SamplePair[] = []
