// GENERATED by scripts/generate-samples.js – do not edit by hand.
// Drop <name>-before.jpg / <name>-after.jpg into public/samples/ and rebuild.
export interface SamplePair {
  id: string
  before: string
  after: string
  title: string
  style: string | null
}

export const samplePairs: SamplePair[] = [
  {
    "id": "podstawka-tablet",
    "before": "/samples/podstawka-tablet-before.webp",
    "after": "/samples/podstawka-tablet-after.webp",
    "title": "Podstawka do tabletu – Akcesoria",
    "style": "Białe tło"
  },
  {
    "id": "projektor",
    "before": "/samples/projektor-before.webp",
    "after": "/samples/projektor-after.webp",
    "title": "Projektor – Elektronika",
    "style": "Białe tło"
  },
  {
    "id": "rolki",
    "before": "/samples/rolki-before.webp",
    "after": "/samples/rolki-after.webp",
    "title": "Rolki – Sport i turystyka",
    "style": "Białe tło"
  }
]
