'use strict';

/**
 * Pull Request creator.
 *
 * Creates a new branch, commits modified files, pushes to GitHub,
 * and opens a PR with a detailed SEO report as the description.
 */

const { execSync } = require('child_process');
const path = require('path');

const REPO_ROOT = path.resolve(__dirname, '..', '..');

// ── Git helpers ───────────────────────────────────────────────────────────────

function run(cmd, opts = {}) {
  return execSync(cmd, {
    encoding: 'utf-8',
    cwd: REPO_ROOT,
    stdio: ['pipe', 'pipe', 'pipe'],
    ...opts,
  }).trim();
}

// ── PR body builder ───────────────────────────────────────────────────────────

function buildPRBody(analysis, appliedChanges, gscData) {
  const { dateRange } = gscData;

  // GSC table — top 10 pages
  const topPagesRows = gscData.pages
    .slice(0, 10)
    .map(
      (p) =>
        `| ${p.url.replace('https://allgrafika.pl', '')} | ${p.impressions} | ${p.clicks} | ${(p.ctr * 100).toFixed(1)}% | ${p.position.toFixed(1)} |`
    )
    .join('\n');

  // Changes table
  const changesSection = appliedChanges.length
    ? appliedChanges
        .map(
          (c, i) => `### ${i + 1}. \`${c.file}\` — \`${c.type}\`

**Reason:** ${c.reason}

**GSC Evidence:** ${c.gsc_evidence}

| | Value |
|---|---|
| **Before** | \`${c.old.substring(0, 160)}\` |
| **After**  | \`${c.new.substring(0, 160)}\` |
`
        )
        .join('\n')
    : '_No changes were applied._';

  return `## 🔍 SEO Agent — Auto-optimization Report

> **Automated PR** — created by the SEO Agent GitHub Action.
> Review each change carefully before merging.

---

### 📅 Run Info

| Field | Value |
|-------|-------|
| Date | ${dateRange.endDate} |
| GSC data range | ${dateRange.startDate} → ${dateRange.endDate} |
| Pages analyzed | ${gscData.pages.length} |
| Changes applied | ${appliedChanges.length} |

---

### 📊 Analysis Summary

${analysis.summary || 'No summary available.'}

| Metric | Value |
|--------|-------|
| Average CTR | ${analysis.avg_ctr_percent?.toFixed(2) ?? 'N/A'}% |
| Average Position | ${analysis.avg_position?.toFixed(1) ?? 'N/A'} |
| Top Opportunity | ${analysis.top_opportunity ?? 'N/A'} |

---

### 📈 GSC Data Snapshot (Top 10 Pages)

| Page | Impressions | Clicks | CTR | Avg Pos |
|------|------------|--------|-----|---------|
${topPagesRows}

---

### ✏️ Applied Changes

${changesSection}

---

### ⚠️ Safety Notes

- All changes are **limited to meta tags, OG tags, and SEO text content only**.
- No application logic, routing, or component structure was modified.
- Every change was validated against the allowlist and screened for dangerous content.
- Changes are minimal and reversible — each is a single string replacement.

---

*Generated by [SEO Agent](.github/workflows/seo-agent.yml) on ${dateRange.endDate}*
`;
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Create a new branch, commit changes, push, and open a PR.
 *
 * @param {object} opts
 * @param {object}   opts.analysis        - AI analysis summary object
 * @param {Array}    opts.applied_changes  - Changes that were successfully applied
 * @param {string[]} opts.modifiedFiles    - Relative paths of modified files
 * @param {object}   opts.gscData          - Full GSC data (for PR body)
 * @param {string}   opts.token            - GitHub token (PAT or GITHUB_TOKEN)
 * @param {string}   opts.repo             - "owner/repo" string
 * @returns {Promise<string>} URL of the created PR
 */
async function createPR({ analysis, applied_changes, modifiedFiles, gscData, token, repo }) {
  const today      = new Date().toISOString().split('T')[0];
  const branchName = `seo-agent/run-${today}`;

  // ── Git setup ───────────────────────────────────────────────────────────
  run("git config user.name 'github-actions[bot]'");
  run("git config user.email 'github-actions[bot]@users.noreply.github.com'");

  // Handle pre-existing branch with the same name
  try {
    run(`git branch -D "${branchName}"`);
  } catch {
    // Branch doesn't exist yet — that's fine
  }

  run(`git checkout -b "${branchName}"`);

  // Stage modified files
  for (const file of modifiedFiles) {
    run(`git add "${file}"`);
  }

  const commitMsg = `seo: auto-optimize meta tags and SEO content (${today})`;
  run(`git commit -m "${commitMsg}"`);

  // ── Push (embed token in remote URL for this operation only) ───────────
  const remoteWithAuth = `https://x-access-token:${token}@github.com/${repo}.git`;
  run(`git push "${remoteWithAuth}" "${branchName}"`);

  // ── Create PR via GitHub REST API ───────────────────────────────────────
  const [owner, repoName] = repo.split('/');
  const prBody = buildPRBody(analysis, applied_changes, gscData);

  const response = await fetch(
    `https://api.github.com/repos/${owner}/${repoName}/pulls`,
    {
      method: 'POST',
      headers: {
        Authorization:  `Bearer ${token}`,
        Accept:         'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        title: `🔍 SEO Agent: auto-optimize meta & headings (${today})`,
        body:  prBody,
        head:  branchName,
        base:  'main',
      }),
    }
  );

  if (!response.ok) {
    const text = await response.text();

    // If a PR already exists for this branch, find it and return its URL
    if (response.status === 422) {
      const existing = await fetch(
        `https://api.github.com/repos/${owner}/${repoName}/pulls?head=${owner}:${branchName}&state=open`,
        { headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github.v3+json' } }
      );
      const prs = await existing.json();
      if (Array.isArray(prs) && prs.length > 0) return prs[0].html_url;
    }

    throw new Error(`Failed to create PR: HTTP ${response.status} — ${text.substring(0, 400)}`);
  }

  const pr = await response.json();
  return pr.html_url;
}

module.exports = { createPR };
